apiVersion: v1
kind: Pod
spec:
  containers:
    - name: kubertest-automated
      image: gcr.io/winter-monolith-281508/kubertest-automated:1.0
      command: ["tail","-f","/dev/null"]
      imagePullPolicy: Always
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
      resources:
        requests:
          memory: "1Gi"
        limits:
          memory: "1Gi"
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock